"use client";

import { useState } from "react";
import styles from "../Styles/FAQ.module.css";



interface FAQItem {
  question: string;
  answer: string;
}


const faqData: FAQItem[] = [
  {
    question: "What is ivvi and how does it work?",
    answer:
      "ivvi is an AI-powered learning tool that automatically converts your lectures and study materials into visual mind maps. Simply upload audio, video, or text, and ivvi's engine transforms the content into structured, easy-to-navigate mind maps — so you can focus on understanding, not note-taking.",
  },
  {
    question: "How can ivvi help students with dyslexia or ADHD?",
    answer:
      "ivvi presents information visually and spatially rather than as dense blocks of text, which significantly reduces cognitive load. Color-coded branches, clear hierarchies, and interactive maps make it easier for students with dyslexia or ADHD to follow along, retain information, and review key concepts at their own pace.",
  },

  {
    question: "Is ivvi only for students with learning differences?",
    answer:
      "Not at all! While ivvi is especially powerful for learners with dyslexia or ADHD, it benefits anyone who wants to study more effectively. Visual learners, busy professionals, and anyone who struggles to keep up with fast-paced lectures will find ivvi a game-changer.",
  },
  {
    question: "How much does ivvi cost and is there a free trial?",
    answer:
      "ivvi offers a free trial so you can explore all its core features before committing. After the trial, affordable subscription plans are available for individual students and institutions. Visit our pricing page for the latest details.",
  },
  {
    question: "Can I use ivvi on multiple devices?",
    answer:
      "Yes! ivvi is fully cross-platform. Your mind maps and account sync seamlessly across desktop, tablet, and mobile, so you can study wherever you are — at home, in class, or on the go.",
  },
  {
    question: "Can I edit or customize my mind maps after the lecture?",
    answer:
      "Absolutely. Every mind map generated by ivvi is fully editable. You can add nodes, reorder branches, change colors, attach notes, and personalize the layout to match the way you think. Your maps, your rules.",
  },
];

function ChevronIcon() {
  return (
    <svg viewBox="0 0 24 24" aria-hidden="true">
      <polyline points="9 18 15 12 9 6" />
    </svg>
  );
}

export default function FAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  const handleToggle = (index: number) => {
    setOpenIndex((prev) => (prev === index ? null : index));
  };



  return (
    <section className={styles.section}>
      <div className={styles.container}>
        <h2 className={styles.title}>Frequently Asked Questions</h2>

        <ul className={styles.list}>
          {faqData.map((item, index) => {
            const isOpen = openIndex === index;

            return (
              <li key={index} className={styles.item}>
                <button
                  className={styles.button}
                  onClick={() => handleToggle(index)}
                  aria-expanded={isOpen}
                  aria-controls={`faq-answer-${index}`}
                >
                  <span className={styles.buttonText}>{item.question}</span>
                  <span
                    className={`${styles.iconWrapper} ${isOpen ? styles.iconOpen : ""}`}
                  >
                    <ChevronIcon />
                  </span>
                </button>

                <div
                  id={`faq-answer-${index}`}
                  role="region"
                  className={`${styles.answerWrapper} ${isOpen ? styles.answerWrapperOpen : ""}`}
                >
                  <div className={styles.answerInner}>
                    <p className={styles.answer}>{item.answer}</p>
                  </div>
                </div>
              </li>
            );
          })}
        </ul>

        <div className={styles.cta}>
          <button className={styles.ctaButton}>Try ivvi Now</button>
        </div>
      </div>
    </section>
  );
}