import React from 'react'
import img from '../../public/images/mind_map.webp'
import StudentsFeatureSection from './StudentsFeatureSection'

function LiveMap() {
	return (
		<StudentsFeatureSection
			titleTag="h3"
			title='Live Mind Map'
			image={img}
			imageAlt='Live mind map generated by ivvi Notes'
			description='As you record, AI creates a visual index of your lecture by selecting keywords and icons that represent main concepts. This dynamic map helps you spot patterns, understand context faster, and retain information more effectively.'
		/>
	)
}

export default LiveMap